### ISSUE TITLE
Does not select item in array

### ISSUE THREAD

**Issue by shripadkulkarnid** [shim0mura/MultiAutoCompleteTextSwift#1]
I complete all procedure .i can see my array but when i select any one item in it it is not select and dosent print on my textfield.Can you replay ASAp
   Thank you in advance.

**Comment by shim0mura** [comment]
Please show your code executing.

**Comment by shripadkulkarnid** [comment]
i wrote same code given in GitHub in viewdidload.
i got array but not able to select item on textfield.
i used ONSELECT method but it is not get execute.

-----
Warm Regards
Shripad D. Kulkarni
Cell:- +91-9689000569,9403408049
Mail:-*shripadkulkarnid@gmail.com <shripadkulkarnid@gmail.com>*

**Comment by shim0mura** [comment]
I can't produce the situation you are facing.
Are you executing EXACT SAME code in https://github.com/shim0mura/MultiAutoCompleteTextSwift/blob/master/MultiAutoCompleteTextSwiftExample/MultiAutoCompleteTextSwiftExample/ViewController.swift ?
What does 'array' mean?

**Comment by shripadkulkarnid** [comment]
i did same in mention .When i make separate project it runs good but in my project i am not able to select WORD  item on textfield

**Comment by shim0mura** [comment]
https://github.com/shim0mura/MultiAutoCompleteTextSwift/blob/master/MultiAutoCompleteTextSwiftExample/sample.gif

You mean if you input 'p' in MultiAutoCompleteTextField named 'textField' in sample code,
 this library suggest 'php', 'perl', 'python' in tableview
then although you select 'php' in tableview, string 'php' does'nt show up in textField, right?

**Comment by shripadkulkarnid** [comment]
Yes now you got it

Warm Regards
Shripad D. Kulkarni
cell:-+91-9689000569,9403408049
Mail:-shripadkulkarnid@gmail.com

**Comment by shim0mura** [comment]
Sorry, I can't still produce the situation you are facing.
You said it runs good in separate project, so your project that doesn't run may affect tableview.
textField.onSelect hook tableView.didSelectRowAtIndexPath of suggested words. If onSelect is not get executed, tapping tableview cell event is disturbed by something.
